name: zap scan

on:
  push:
    branches:
      - main 
jobs:
  zap_scan:
    runs-on: ubuntu-latest
      
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Start web application
        run: |

           java -jar build/libs/java-app-1.0-SNAPSHOT.jar & # For example, if your application is a Spring Boot app:
    
      - name: Wait for application to start
        run: sleep 5
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://www.zaproxy.org/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'